#!/bin/sh

# Visuals
setbg &
xrdb -merge "$XRESOURCES" &

# Input
$HOME/.local/bin/inputsettings &

# Programs
dunst &
transmission-daemon &
picom &
#pipewire &
pulseaudio &
dwmblocks &
exec ssh-agent dwm 2>&1 > "$XDG_CACHE_HOME/dwm/dwm.log"
